version: "0.0.4"
engines: ['julia']

project:
  type: book

book:
  title: "Using Julia for Introductory Statistics"
  author: "John Verzani"
  date: now
  search: true
  repo-url: https://github.com/jverzani/UsingJ
  repo-branch: master
  repo-actions: [edit, issue]
  google-analytics: "G-KS515LKBGZ"
#  downloads: pdf
  page-footer:
    right: |
      © Copyright 2023, John Verzani. All rights reserved.
  chapters:
    - index.qmd
    - EDA/univariate-julia.qmd
    - EDA/tabular-data-julia.qmd
    - EDA/bivariate-julia.qmd
    - EDA/categorical-data-julia.qmd
    - EDA/makie.qmd
    - Inference/distributions.qmd
    - Inference/inference.qmd
    - LinearModels/linear-regression.qmd
    - references.qmd
#        - LinearModels/glm.qmd

bibliography: references.bib
csl: the-american-statistician.csl


format:
  html:
    theme: spacelab
    number-depth: 3
    toc-depth: 3
    link-external-newwindow: true
#    fig-width: 6
#    fig-height: 4
#  pdf:
#    pdf-engine: xelatex
#    fontfamily: libertinus # librecaslon
#    toc: true
#    number-section: true
#    color-links: true
#    classoption: [oneside]
#    keep-tex: true
#    tbl-cap-location: top
#    fig-cap-location: top
#    geometry:
#      - heightrounded
#    colorlinks: true
#    include-in-header: packages.tex
#    include-before-body: definitions.tex


execute:
  warning: false
  error: false
#  freeze: auto
  cache: false
