project:
  type: book

book:
  title: "Using Julia for Introductory Statistics"
  author: "John Verzani"
  bibliography: references.bib
  date: now
  number-sections: true
  search: true
  repo-url: https://github.com/jverzani/UsingJ
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: pdf
  chapters:
    - index.qmd
    - part: "Exploratory Data Analysis"
      chapters:
        - EDA/univariate-julia.qmd
        - EDA/tabular-data-julia.qmd
        - EDA/bivariate-julia.qmd
        - EDA/categorical-data-julia.qmd
        - EDA/makie.qmd
    - part: "Inference"
      chapters:
        - Inference/distributions.qmd
        - Inference/inference.qmd
    - part: "Linear Models"
      chapters:
        - LinearModels/linear-regression.qmd
#        - LinearModels/anova.qmd
#        - LinearModels/glm.qmd
format:
  html:
    theme: spacelab
    number-depth: 3
    toc-depth: 3
    link-external-newwindow: true
    fig-width: 6
    fig-height: 4
  pdf: # need to skip over unicode missing errors...
    pdf-engine: xelatex
    fontfamily: libertinus # librecaslon
    documentclass: book
    classoption: [oneside]
    keep-tex: true
    tbl-cap-location: top
    fig-cap-location: top
    geometry:
      - heightrounded
    colorlinks: true
    include-in-header: packages.tex
    include-before-body: definitions.tex
    fig-width: 4
    fig-height: 3

execute:
  warning: false
  error: true
  freeze: auto
